### ISSUE TITLE
Is there a way to save without triggering any events?

### ISSUE THREAD

**Issue by primeapple** [okuuva/auto-save.nvim#15]
Say you are using `lazy.nvim` aus Plugin Manager. It compiles after every safe, which makes it really hard to use together with `auto-save`, because it will often compile when the syntax is not correct yet.

I would like to have a way, where I can disable the triggering of `...Write` events when auto-save is executed. So that lazy will only recompile if I manually save (or on the next startup).

The same can be thought with format. I don't want to format on Autosave, but rather on manual save (or even on Immediate Save, when leaving the buffer).

**Comment by okuuva** [comment]
I once tried to implement that with [`noautocmd`](https://neovim.io/doc/user/autocmd.html#%3Anoautocmd) but didn't manage to get it working. That was a while ago though and I think there might've been a bug in `auto-save.nvim` then that has since been fixed. That or I was using some other auto save plugin at the time. I've had less time to work on `auto-save.nvim` lately that I would've liked but this is something that should definitely be
a) possible and
b) documented in the readme.

**Comment by primeapple** [comment]
I played around with it a bit. It works by adding `noautocmd` in front of the save command in `init.lua`.

For lazy this doesn't change anything, since it works with timers instead of Autocmds (god knows why ;-) ).

Two options to implement this feature:
1. Create a `execute_save_command` function that builds the correct string (something like `noautocmd silent! write`)
2. Give the user the option to supply the `save_command` in the config. This seems cleaner, but has the drawback, that some write commands need to be executed within `nvim_buf_call`. But maybe we could just execute always execute the command within this wrapper, I'm unsure of the drawbacks.

What do you think?

**Comment by okuuva** [comment]
> I played around with it a bit. It works by adding `noautocmd` in front of the save command in `init.lua`.
> 
> For lazy this doesn't change anything, since it works with timers instead of Autocmds (god knows why ;-) ).
> 
> Two options to implement this feature:
> 
>     1. Create a `execute_save_command` function that builds the correct string (something like `noautocmd silent! write`)
> 
>     2. Give the user the option to supply the `save_command` in the config. This seems cleaner, but has the drawback, that some write commands need to be executed within `nvim_buf_call`. But maybe we could just execute always execute the command within this wrapper, I'm unsure of the drawbacks.
> 
> 
> What do you think?

No strong opinions right now. I'm on holiday and will be back home this weekend, I'll take a closer look at the options then.

**Comment by okuuva** [comment]
Sorry for the delay, have been busy ever since I got home.

> I played around with it a bit. It works by adding noautocmd in front of the save command in init.lua.
> For lazy this doesn't change anything, since it works with timers instead of Autocmds (god knows why ;-) ).

I'm not sure I follow. So `lazy.nvim` triggers compilation when the configuration file(s) are saved but it's not done with an autocommand? How do they track it then?

>Two options to implement this feature:
>
> 1. Create a execute_save_command function that builds the correct string (something like noautocmd silent! write)
> 2. Give the user the option to supply the save_command in the config. This seems cleaner, but has the drawback, that some write commands need to be executed within nvim_buf_call. But maybe we could just execute always execute the command within this wrapper, I'm unsure of the drawbacks.

Maybe I'm missing something, but how would option 1. differ from just adding `noautocmd` to the save command in `init.lua`? Not saying we should hard code it there (or maybe we should?) but I got the impression it doesn't work with `lazy.nvim` for whatever reason.

I'm not really fond of idea of making the actual save command user configurable. It adds complexity to a plugin that should be simple and easy to use. It would also require some refactoring since I don't think having a separate config option for saving all buffers vs just the active one would make sense with a custom save command. If you can think of more use cases for it than just disabling auto commands we can consider it but just for this use case it sounds overkill to me.

Thank you once again for taking the time to investigate this!

**Comment by primeapple** [comment]
> I'm not sure I follow. So lazy.nvim triggers compilation when the configuration file(s) are saved but it's not done with an autocommand? How do they track it then?

Lazy has the option to disable the config changes check:
```lua
  change_detection = {
    -- automatically check for config file changes and reload the ui
    enabled = true,
```

I checked where it is getting used and this is the only use: https://github.com/folke/lazy.nvim/blob/f8611632d0f9c6818e8eb54f9bcd1dad122b5a7f/lua/lazy/core/config.lua#L245

If we dig further we find this: https://github.com/folke/lazy.nvim/blob/f8611632d0f9c6818e8eb54f9bcd1dad122b5a7f/lua/lazy/manage/reloader.lua#L14
As we see, there is a timer running, that is checking every 2000ms for changes to the config. So it's not done via autocommands.

> Maybe I'm missing something, but how would option 1. differ from just adding noautocmd to the save command in init.lua?

There are actually two save commands because we have an option to save all files. So you'd end up with the following cases:

1. Write all with `noautocmd`
2. Write all without `noautocmd`
3. Write single file with `noautocmd`
4. Write single file without `noautocmd`

That's easy implemented, I just wondered if we might add other modifiers in the future. Then a function to build the save command string would be neat ;-)

**Comment by okuuva** [comment]
> > I'm not sure I follow. So lazy.nvim triggers compilation when the configuration file(s) are saved but it's not done with an autocommand? How do they track it then?
> 
> Lazy has the option to disable the config changes check:
> 
> ```lua
>   change_detection = {
>     -- automatically check for config file changes and reload the ui
>     enabled = true,
> ```
> 
> I checked where it is getting used and this is the only use: [folke/lazy.nvim@`f861163`/lua/lazy/core/config.lua#L245](https://github.com/folke/lazy.nvim/blob/f8611632d0f9c6818e8eb54f9bcd1dad122b5a7f/lua/lazy/core/config.lua#L245)
> 
> If we dig further we find this: [folke/lazy.nvim@`f861163`/lua/lazy/manage/reloader.lua#L14](https://github.com/folke/lazy.nvim/blob/f8611632d0f9c6818e8eb54f9bcd1dad122b5a7f/lua/lazy/manage/reloader.lua#L14) As we see, there is a timer running, that is checking every 2000ms for changes to the config. So it's not done via autocommands.

Ah, ok. That's interesting, wonder why folke went with that instead of listening to save events.

> > Maybe I'm missing something, but how would option 1. differ from just adding noautocmd to the save command in init.lua?
> 
> There are actually two save commands because we have an option to save all files. So you'd end up with the following cases:
> 
>     1. Write all with `noautocmd`
> 
>     2. Write all without `noautocmd`
> 
>     3. Write single file with `noautocmd`
> 
>     4. Write single file without `noautocmd`
> 
> 
> That's easy implemented, I just wondered if we might add other modifiers in the future. Then a function to build the save command string would be neat ;-)

Ah ok got it now! Somehow the two things (lazy.nvim config autocompile and `noautocmd`) got mixed in my head and I thought the two different options would somehow solve both 😅 But since there's no way around the lazy.nvim thing then I'd definitely go with the option 1.
