### ISSUE TITLE
Auto save works differently compared to `:w<CR>`

### ISSUE THREAD

**Issue by Andrew15-5** [okuuva/auto-save.nvim#41]
Continuing https://github.com/okuuva/auto-save.nvim/issues/40#issuecomment-1742183400, I have found one problem with this fork (which isn't present in the original project). When I use `coc.nvim` with `coc-rust-analyzer` some errors/warning are not updated unless I use `:w<CR>` or the original plugin.

Here I created a new Rust project and opened the `main.rs`. Then I waited for LSP server to start, wrote a new line and exited insert mode:

![image](https://github.com/okuuva/auto-save.nvim/assets/37143421/029bc003-9fa4-42e1-af0b-6204a20a5032)

And here what I get when I write `:w<CR>`:

![image](https://github.com/okuuva/auto-save.nvim/assets/37143421/e4256f3e-b624-4b8e-88d7-bc3e99dc2250)

So the problem is with the way this fork saves the file/buffer. I think some event just isn't triggered, which is fine with me if it didn't degrade my dev UX. What could be the problem?

<details><summary>Original project config that works</summary>

```lua
require("auto-save").setup {
  execution_message = { message = function() return "" end },
  trigger_events = { "InsertLeave", "TextChanged" },
}
```

</details>

<details><summary>The fork's config that doesn't work</summary>

```lua
require("auto-save").setup {
  enabled = true,
  execution_message = { enabled = false },
  trigger_events = {
    immediate_save = { "InsertLeave", "TextChanged" },
    defer_save = {},
    cancel_defered_save = {},
  },
  debounce_delay = 0,
}
```

</details>

**Comment by primeapple** [comment]
To emulate the original plugins behaviour, set the following:
```lua
  trigger_events = {
    immediate_save = {},
    defer_save = { "InsertLeave", "TextChanged" },
    cancel_defered_save = {},
  },
  debounce_delay = 125,
```

Does this solve the problem?

**Comment by Andrew15-5** [comment]
> Does this solve the problem?

Yes!

But can you provide some information on why this is the case? Why instead of immediate I need to switch to defer with 125 ms delay?

**Comment by primeapple** [comment]
I don't know, I use neither `coc.nvim` nor `coc-rust-analyzer`. My guess is that the save is to "fast", so the rust lsp has not picked up the changes yet. It probably has an autocommand after save, to add diagnostics for the current buffer.

That's the reason for the defaults and for the delayed safe btw. I wouldn't recommend to immediate save after every text change. People have tried and they failed, that's the whole reason for this plugin :)

Feel free to close

**Comment by Andrew15-5** [comment]
> To emulate the original plugins behaviour, set the following:
> 
> ```lua
>   trigger_events = {
>     immediate_save = {},
>     defer_save = { "InsertLeave", "TextChanged" },
>     cancel_defered_save = {},
>   },
>   debounce_delay = 125,
> ```

You should probably add this to the readme file to provide a smoother transition for those, who come from the original project, like me.

**Comment by primeapple** [comment]
> You should probably add this to the readme file to provide a smoother transition for those, who come from the original project, like me.

The whole point of the fork is to provide functionality that solves the problems of the original plugin (use `debouncing` for saving instead of `throtteling`). Your problem existed because you didn't configure the plugin correctly.

Our defaults should work better than the emulated settings of the original plugin every day of the week.

**Comment by Andrew15-5** [comment]
No, I did configure the plugin correctly. I just didn't know that 125 ms delay is the minimal optimal/safe delay for other tools that watch for changes to work correctly. Your default is 1000 which is ridiculously slow if we are talking live preview with Typst. And 0 ms delay breaks some/all the tools (like Rust LSP). Only after you told me the defaults of the original project, everything worked like a charm (snappy, but not "brakey").

**Comment by primeapple** [comment]
You configured it wrong in a way that you used `immediate_save` which is "to fast" for most dependent plugins.

I think you would be fine if you would take the original config and only change the delay to 125ms. Right now you are not using any cancel events, which may cause to much load on your external tools. Think of typing `daw` 10 times, with 100ms inbetween. This would cause 8 save events which may overwhelm external watchers. With the default config and 125ms delay you would end up with only one save, the one at the end.

**Comment by okuuva** [comment]
Ok guys, let's try keep the communications civil. Don't know about you but English isn't the first language for me so some things might come out a bit strong or even rude even though that's not my intention. I hope and believe it's not the intention for either of you either :)

I agree with @primeapple that the current defaults should work for most of the user most of the time. And they should work better than the ones in the old repo. But what I haven't considered up until now is that people that are switching over from the original plugin might have custom settings that made sense there but work poorly or not at all here. Might be because the settings have been deprecated or they were used as a workaround for some bug or a lack of feature that's not necessary here anymore.

So while I don't think it's necessarily a good idea to include a configuration snippet on how to emulate the behavior of the old plugin 1-to-1 in the readme, we should definitely write a migration guide, however basic. For example: we tend to get some issue reports on something not working right. The problem usually is that the user hasn't updated their plugins and restarted nvim after switching the repo in their configuration file, so they are really still running the old version of the plugin. That's something that's really easy to overlook (have done it myself a few times 😅 ). So we should point out in the readme that setting the debounce delay to some very low value is bound to break things and modifying `defer_save` and `immediate_save` event tables is probably a better way to achieve faster saves. So: thank you @Andrew15-5 for the issue report and helping to resolve it, and thanks for the suggestion on improving the documentation as well. Also huge thanks to @primeapple for your continuous efforts on maintaining and improving auto-save.nvim.

I'll try to get around to writing the migration guide this week, will ping you both for feedback once I get the PR out.

**Comment by Andrew15-5** [comment]
> You configured it wrong in a way that you used `immediate_save` which is "to fast" for most dependent plugins.

Right, that I forgot. I primarily focused on the delay option. I generally only had this defined:

```vim
let g:auto_save_events = ["InsertLeave", "TextChanged"]
```

So I just _assumed_ that I want an immediate save, because "why would I wait? Gotta go fast!" (*file saving goes brrrr*). Plus the default `defer_save` delay was too big and maybe `0` didn't work either, so in any case, I used `immediate_save` in the end, until the current issue was resolved. So this is also the kind of thing that should be mentioned in the "migration guide".
