### ISSUE TITLE
auto-save not working on "TextChanged"

### ISSUE THREAD

**Issue by parik-shit** [okuuva/auto-save.nvim#43]
```
{
"okuuva/auto-save.nvim",
cmd = "ASToggle", -- optional for lazy loading on command
event = { "InsertLeave", "TextChanged" }, -- optional for lazy loading on trigger events
opts = {

},
},
```
auto-save is only working when I leave Insert Mode

**Comment by parik-shit** [comment]
Okay, so I added `FocusLost` event but it is still not working. I guess immediate save has already been implemented but seems to be having on my neovim config.

**Comment by okuuva** [comment]
>auto-save is only working when I leave Insert Mode

Could you give a bit more details on how exactly it isn't working? So it's not auto-saving at all or it's not auto-saving immediately?

>Okay, so I added FocusLost event but it is still not working. I guess immediate save has already been implemented but seems to be having on my neovim config.

By default InsertLeave and TextChanged only trigger deferred save which saves the buffer automatically after debounce delay unless it gets cancelled by an event listed in the trigger_events.cancel_deferred_save table (by default only InsertEnter). If you want InsertLeave to trigger an automatic save you need to add it to trigger_events.immediate_save table and remove it from the trigger_events.defer_save table so that it doesn't trigger two saves. Check the [configuration](https://github.com/okuuva/auto-save.nvim#%EF%B8%8F-configuration) section in the readme for more details.

And if you migrated from pocco81/auto-save.nvim, make sure you update the plugins and restart neovim. Otherwise lazy might still be using the old version of the plugin.

**Comment by parik-shit** [comment]
It started working, IDK what was the problem. 
Thanks.
